/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BackgroundProcess */

#ifndef _Included_BackgroundProcess
#define _Included_BackgroundProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BackgroundProcess
 * Method:    mainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BackgroundProcess_mainLoop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
