/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onelog_BackgroundProcess */

#ifndef _Included_onelog_BackgroundProcess
#define _Included_onelog_BackgroundProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     onelog_BackgroundProcess
 * Method:    mainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_onelog_BackgroundProcess_mainLoop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
